Switch push-based deploy to a checkout-per-push model
The problem with doing an archive/untar operation onto an existing directory
(/etc/puppet) is that deleted files never go away.  This doesn't come up often,
but when it does it produces all sorts of hard-to-debug problems.  So we do
this instead.  Sadly, it requires a bit of wrangling to make librarian-puppet
play nicely with the other children and not re-install every module on every
run.

This commit also adds a bunch of other nice features that I've had floating
around for a while.

diff --git a/templates/etc/puppet/repo/hooks/update b/templates/etc/puppet/repo/hooks/update
--- a/templates/etc/puppet/repo/hooks/update
+++ b/templates/etc/puppet/repo/hooks/update
@@ -6,19 +6,9 @@ REF="$1"
 OLDREV="$2"
 NEWREV="$3"
 
-cd /etc/puppet
-
-git --git-dir /etc/puppet/repo archive --format=tar "$NEWREV" | sudo tar xf -
-
-sudo librarian-puppet install
-
-sudo puppet apply --show_diff <%= @future_parser ? "--parser=future " : "" %>./nodes
-
-# Apply puppet to all containers on the node, too
-if [ -d /srv/lxc ]; then
-	for d in /srv/lxc/*; do
-		if [ -f "$d/config" ]; then
-			sudo lxc-attach -n $(basename $d) -- puppet apply --show_diff <%= @future_parser ? "--parser=future " : "" %>/etc/puppet/nodes
-		fi
-	done
+if [ "$REF" != "refs/heads/master" ]; then
+	echo "ERROR: must push to master" >&2
+	exit 1
 fi
+
+sudo /etc/puppet/deploy -v -r "$NEWREV"
